name: Build QOL Framework

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch Verified Community Binary
      run: |
        mkdir -p FinalOutput
        curl -L -o FinalOutput/QOL.dll "https://github.com/ricardosouzag/ModInstaller/raw/master/Mods/QOL.dll"

    - name: Upload Finished Mod
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-QOL
        path: FinalOutput/QOL.dll
